namespace ATravelersGuideToSerdan.Migrations
{
    using ATravelersGuideToSerdan.Models;
    using System;
    using System.Collections.Generic;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<ATravelersGuideToSerdan.Models.SerdanDb>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
        }

        protected override void Seed(ATravelersGuideToSerdan.Models.SerdanDb context)
        {
            //  This method will be called after migrating to the latest version.

            //  You can use the DbSet<T>.AddOrUpdate() helper extension method 
            //  to avoid creating duplicate seed data.
            context.NPCs.AddOrUpdate(i => i.NpcName,
                new NPC
                {
                    NpcName = "David",
                    NpcEvenKnownAs = "Farbror Blå",
                    NpcAlias = "FarFar",
                    NpcDescriptivePhrase = "David är urfadern för alla Serdan.",
                    NpcLooks = "En äldre man med vit skägg.",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Aisela",
                    NpcRace = "Serdan",
                    NpcIsAPlayer = false,
                    NpcFamily = "Serdan",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 8,
                    NpcsFather = 5,
                    NpcsSerdanEdlosiChildren = new List<int> { 3, 4 },
                    NpcsRegularChildren = new List<int> { 6, 7 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 4, 3 },
                    NpcAllies = new List<int> { 4, 3 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                new NPC
                {
                    NpcName = "Xara",
                    NpcEvenKnownAs = "Mormor Röd",
                    NpcAlias = "MorMor",
                    NpcDescriptivePhrase = "Xara är urmodern för alla Edlosi.",
                    NpcLooks = "En äldre kvinna med vit långt hår.",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Kalandri",
                    NpcRace = "Edlosi",
                    NpcIsAPlayer = false,
                    NpcFamily = "Edlosi",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 10,
                    NpcsFather = 11,
                    NpcsSerdanEdlosiChildren = new List<int> { 14, 15, 16, 17 },
                    NpcsRegularChildren = new List<int> { 103, 104, 105 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 10, 11 },
                    NpcAllies = new List<int> { 10, 11 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                new NPC
                {
                    NpcName = "Julian",
                    NpcEvenKnownAs = "Drakens Arm",
                    NpcAlias = "Julle",
                    NpcDescriptivePhrase = "Julian är spionmästaren.",
                    NpcLooks = "Man med bakåtslickat hår",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Aisela",
                    NpcRace = "Serdan",
                    NpcIsAPlayer = false,
                    NpcFamily = "Serdan",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 10,
                    NpcsFather = 1,
                    NpcsSerdanEdlosiChildren = new List<int> { 14, 15, 16, 17 },
                    NpcsRegularChildren = new List<int> { 103, 104, 105 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 10, 11 },
                    NpcAllies = new List<int> { 10, 11 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                new NPC
                {
                    NpcName = "Mildred",
                    NpcEvenKnownAs = "Gröna Häxan",
                    NpcAlias = "Tant Blå",
                    NpcDescriptivePhrase = "Mildred är en drakvän.",
                    NpcLooks = "En kvinna med svart långt hår och grön klänning.",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Aisela",
                    NpcRace = "Serdan",
                    NpcIsAPlayer = false,
                    NpcFamily = "Serdan",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 0,
                    NpcsFather = 1,
                    NpcsSerdanEdlosiChildren = new List<int> { 8,9 },
                    NpcsRegularChildren = new List<int> { 10,11 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 12, 13 },
                    NpcAllies = new List<int> { 14, 15 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                new NPC
                {
                    NpcName = "Anders",
                    NpcEvenKnownAs = "Spelledaren",
                    NpcAlias = "Berättaren",
                    NpcDescriptivePhrase = "Puppetmaster",
                    NpcLooks = "En man med knivskarpt intellekt.",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Aisela",
                    NpcRace = "Serdan",
                    NpcIsAPlayer = false,
                    NpcFamily = "Serdan",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 0,
                    NpcsFather = 1,
                    NpcsSerdanEdlosiChildren = new List<int> { 8, 9 },
                    NpcsRegularChildren = new List<int> { 10, 11 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 12, 13 },
                    NpcAllies = new List<int> { 14, 15 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                new NPC
                {
                    NpcName = "Melindra",
                    NpcEvenKnownAs = "Grå Häxan",
                    NpcAlias = "Blå",
                    NpcDescriptivePhrase = "Melindra är huvudet för en magiorder.",
                    NpcLooks = "En kvinna med Brunt långt hår och röd klänning.",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Aisela",
                    NpcRace = "human",
                    NpcIsAPlayer = false,
                    NpcFamily = "Serdan",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 0,
                    NpcsFather = 1,
                    NpcsSerdanEdlosiChildren = new List<int> { 8, 9 },
                    NpcsRegularChildren = new List<int> { 10, 11 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 12, 13 },
                    NpcAllies = new List<int> { 14, 15 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                new NPC
                {
                    NpcName = "Thomas",
                    NpcEvenKnownAs = "Royal Capten",
                    NpcAlias = "Farbror Stål",
                    NpcDescriptivePhrase = "Thomas leder vakten i Aisela.",
                    NpcLooks = "En man som vuxit ihop med sin rustning.",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Aisela",
                    NpcRace = "Human",
                    NpcIsAPlayer = false,
                    NpcFamily = "Serdan",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 0,
                    NpcsFather = 1,
                    NpcsSerdanEdlosiChildren = new List<int> { 8, 9 },
                    NpcsRegularChildren = new List<int> { 10, 11 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 12, 13 },
                    NpcAllies = new List<int> { 14, 15 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                },
                new NPC
                {
                    NpcName = "Mia",
                    NpcEvenKnownAs = "kronikörern",
                    NpcAlias = "Tant Berättare",
                    NpcDescriptivePhrase = "Mia är oftast i Biblioteket",
                    NpcLooks = "En kvinna med blont hår och grön klänning.",
                    NpcDescription = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcCurrentResidence = "Aisela",
                    NpcRace = "Aet",
                    NpcIsAPlayer = false,
                    NpcFamily = "Aet",
                    NpcArchetyp = 1,
                    NpcKilledBy = 0,
                    NpcBehaviour = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAsAParent = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcGoal = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInBattle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcsMother = 0,
                    NpcsFather = 1,
                    NpcsSerdanEdlosiChildren = new List<int> { 8, 9 },
                    NpcsRegularChildren = new List<int> { 10, 11 },
                    NpcRegardingAets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDemons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingDragons = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingGrips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcRegardingOthers = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcFriends = new List<int> { 12, 13 },
                    NpcAllies = new List<int> { 14, 15 },
                    NpcRivals = new List<int> { 50, 51, 52, 53, 54 },
                    NpcEnemies = new List<int> { 60, 61, 62 },
                    NpcOtherResideces = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcInTheHistory = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcSecrets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                    NpcAssets = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
                });
            context.SaveChanges();

            context.NpcStats.AddOrUpdate(i => i.NpcId,
                new NpcStat
                {
                    NpcId = 1,
                    KoordinationMotorikTot = 100,
                    KoordinationMotorikUts = 100,
                    WeaponValue = 100,
                    WeaponTp = 10,
                    WeaponExp = 20,
                    WeaponSkills = "weaponskill1, weaponskill2",
                    WeaponTTp = 5,
                    WeaponTalang = "Talang1, talang2",
                    BalisticValue = 100,
                    BalisticTp = 10,
                    BalisticExp = 20,
                    BalisticSkills = "Balisticskill",
                    BalisticTTp = 5,
                    BalisticTalang = "Talang3",
                    FineMotorValue = 100,
                    FineMotorTp = 10,
                    FineMotorExp = 20,
                    FineMotorSkills = "FineMotorSkill1",
                    FineMotorTTp = 5,
                    FineMotorTalang = "FineMotorTalang1",
                    PhysiqueTot = 100,
                    PhysiqueUts = 100,
                    PhysicsValue = 100,
                    PhysicsTp = 10,
                    PhysicsExp = 20,
                    PhysicsSkills = "Physicalskill1",
                    PhysicsTTp = 5,
                    PhysicsTalang = "PhysicsTalang1",
                    StrenghtValue = 100,
                    StrenghtTp = 10,
                    StrenghtExp = 20,
                    StrenghtSkills = "Strengthskill1",
                    StrenghtTTp = 5,
                    StrenghtTalang = "StrengthTalang1",
                    MobilityValue = 100,
                    MobilityTp = 10,
                    MobilityExp = 20,
                    MobilitySkills = "Mobilityskill1",
                    MobilityTTp = 5,
                    MobilityTalang = "MobilityTalang1",
                    PsykeTot = 100,
                    PsykeUts = 100,
                    WillValue = 100,
                    WillTp = 10,
                    WillExp = 20,
                    WillSkills = "willskills1",
                    WillTTp = 5,
                    WillTalang = "WillTalang1",
                    CreativityValue = 100,
                    CreativityTp = 100,
                    CreativityExp = 20,
                    CreativitySkills = "Creativityskills1",
                    CreativityTTp = 5,
                    CreativityTalang = "creativityTalang1",
                    EducationValue = 100,
                    EducationTp = 10,
                    EducationExp = 20,
                    EducationSkills = "EducationSkill1",
                    EducationTTp = 5,
                    EducationTalang = "EducationTalang1",
                    PerceptionTot = 100,
                    PerceptionUts = 100,
                    IntuitionValue = 100,
                    IntuitionTp = 10,
                    IntuitionExp = 20,
                    IntuitionSkills = "IntuitionSkill1",
                    IntuitionTTp = 5,
                    IntuitionTalang = "IntuitionTalang1",
                    MagicVisionValue = 100,
                    MagicVisionTp = 10,
                    MagicVisionExp = 20,
                    MagicVisionSkills = "Magicskills1",
                    MagicVisionTTp = 5,
                    MagicVisionTalang = "MagicTalang1",
                    AttentionValue = 100,
                    AttentionTp = 10,
                    AttentionExp = 20,
                    AttentionSkills = "Attentionskill1",
                    AttentionTTp = 5,
                    AttentionTalang = "AttentionTalang1",
                    SocialTot = 100,
                    SocialUts = 100,
                    CharismaValue = 100,
                    CharismaTp = 10,
                    CharismaExp = 20,
                    CharismaSkills = "Charismaskill1",
                    CharismaTTp = 5,
                    CharismaTalang = "CharismaTalang1",
                    InsightValue = 100,
                    InsightTp = 10,
                    InsightExp = 20,
                    InsightSkills = "InsightSkill1",
                    InsightTTp = 5,
                    InsightTalang = "InsightTalang1",
                    ResistanceValue = 100,
                    ResistanceTp = 10,
                    ResistanceExp = 20,
                    ResistanceSkills = "resistanceskill1",
                    ResistanceTTp = 5,
                    ResistanceTalang = "ResistanceTalang1",
                    PhysicalDamageMax = 200,
                    PhysicalDamage = 50,
                    SoulDamageMax = 200,
                    SoulDamage = 50

                });
            context.SaveChanges();

        }
    }
}
